// lib/services/local_storage_service.dart
import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_model.dart';
import '../models/transaction_model.dart';
import '../models/family_model.dart';
import '../models/budget_model.dart';
import '../models/goal_model.dart';
import '../models/category_model.dart';
import '../models/notification_model.dart';
import '../models/backup_model.dart';
import '../models/transfer_model.dart';
import '../models/report_model.dart';

class LocalStorageService {
  static const String _userBox = 'user_box';
  static const String _transactionBox = 'transaction_box';
  static const String _familyBox = 'family_box';
  static const String _budgetBox = 'budget_box';
  static const String _goalBox = 'goal_box';
  static const String _categoryBox = 'category_box';
  static const String _notificationBox = 'notification_box';
  static const String _backupBox = 'backup_box';
  static const String _transferBox = 'transfer_box';
  static const String _reportBox = 'report_box';
  static const String _prefKey = 'finfam_prefs';

  static late Box _userBoxInstance;
  static late Box _transactionBoxInstance;
  static late Box _familyBoxInstance;
  static late Box _budgetBoxInstance;
  static late Box _goalBoxInstance;
  static late Box _categoryBoxInstance;
  static late Box _notificationBoxInstance;
  static late Box _backupBoxInstance;
  static late Box _transferBoxInstance;
  static late Box _reportBoxInstance;
  static late SharedPreferences _prefs;

  static bool _initialized = false;

  // ============================================================
  // INITIALIZATION
  // ============================================================

  static Future<void> init() async {
    if (_initialized) return;

    await Hive.initFlutter();
    
    // Register adapters (generated by build_runner)
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(TransactionModelAdapter());
    // ... etc

    _userBoxInstance = await Hive.openBox(_userBox);
    _transactionBoxInstance = await Hive.openBox(_transactionBox);
    _familyBoxInstance = await Hive.openBox(_familyBox);
    _budgetBoxInstance = await Hive.openBox(_budgetBox);
    _goalBoxInstance = await Hive.openBox(_goalBox);
    _categoryBoxInstance = await Hive.openBox(_categoryBox);
    _notificationBoxInstance = await Hive.openBox(_notificationBox);
    _backupBoxInstance = await Hive.openBox(_backupBox);
    _transferBoxInstance = await Hive.openBox(_transferBox);
    _reportBoxInstance = await Hive.openBox(_reportBox);
    
    _prefs = await SharedPreferences.getInstance();
    _initialized = true;
  }

  // ============================================================
  // USER
  // ============================================================

  static Future<void> saveUser(UserModel user) async {
    await _userBoxInstance.put(user.id, jsonEncode(user.toJson()));
  }

  static Future<UserModel?> getUser(String id) async {
    final data = _userBoxInstance.get(id);
    if (data == null) return null;
    return UserModel.fromJson(jsonDecode(data));
  }

  static Future<List<UserModel>> getAllUsers() async {
    final users = <UserModel>[];
    for (var key in _userBoxInstance.keys) {
      final data = _userBoxInstance.get(key);
      if (data != null) {
        users.add(UserModel.fromJson(jsonDecode(data)));
      }
    }
    return users;
  }

  static Future<void> deleteUser(String id) async {
    await _userBoxInstance.delete(id);
  }

  static Future<void> clearUsers() async {
    await _userBoxInstance.clear();
  }

  // ============================================================
  // TRANSACTIONS
  // ============================================================

  static Future<void> saveTransaction(TransactionModel transaction) async {
    await _transactionBoxInstance.put(transaction.id, jsonEncode(transaction.toJson()));
  }

  static Future<TransactionModel?> getTransaction(String id) async {
    final data = _transactionBoxInstance.get(id);
    if (data == null) return null;
    return TransactionModel.fromJson(jsonDecode(data));
  }

  static Future<List<TransactionModel>> getAllTransactions() async {
    final transactions = <TransactionModel>[];
    for (var key in _transactionBoxInstance.keys) {
      final data = _transactionBoxInstance.get(key);
      if (data != null) {
        transactions.add(TransactionModel.fromJson(jsonDecode(data)));
      }
    }
    return transactions;
  }

  static Future<List<TransactionModel>> getTransactionsByUser(String userId) async {
    final all = await getAllTransactions();
    return all.where((t) => t.userId == userId).toList();
  }

  static Future<void> deleteTransaction(String id) async {
    await _transactionBoxInstance.delete(id);
  }

  static Future<void> clearTransactions() async {
    await _transactionBoxInstance.clear();
  }

  // ============================================================
  // FAMILIES
  // ============================================================

  static Future<void> saveFamily(FamilyModel family) async {
    await _familyBoxInstance.put(family.id, jsonEncode(family.toJson()));
  }

  static Future<FamilyModel?> getFamily(String id) async {
    final data = _familyBoxInstance.get(id);
    if (data == null) return null;
    return FamilyModel.fromJson(jsonDecode(data));
  }

  static Future<List<FamilyModel>> getAllFamilies() async {
    final families = <FamilyModel>[];
    for (var key in _familyBoxInstance.keys) {
      final data = _familyBoxInstance.get(key);
      if (data != null) {
        families.add(FamilyModel.fromJson(jsonDecode(data)));
      }
    }
    return families;
  }

  static Future<List<FamilyModel>> getFamiliesByUser(String userId) async {
    final all = await getAllFamilies();
    return all.where((f) => f.members?.any((m) => m.userId == userId) ?? false).toList();
  }

  static Future<void> deleteFamily(String id) async {
    await _familyBoxInstance.delete(id);
  }

  static Future<void> clearFamilies() async {
    await _familyBoxInstance.clear();
  }

  // ============================================================
  // BUDGETS
  // ============================================================

  static Future<void> saveBudget(BudgetModel budget) async {
    await _budgetBoxInstance.put(budget.id, jsonEncode(budget.toJson()));
  }

  static Future<BudgetModel?> getBudget(String id) async {
    final data = _budgetBoxInstance.get(id);
    if (data == null) return null;
    return BudgetModel.fromJson(jsonDecode(data));
  }

  static Future<List<BudgetModel>> getAllBudgets() async {
    final budgets = <BudgetModel>[];
    for (var key in _budgetBoxInstance.keys) {
      final data = _budgetBoxInstance.get(key);
      if (data != null) {
        budgets.add(BudgetModel.fromJson(jsonDecode(data)));
      }
    }
    return budgets;
  }

  static Future<List<BudgetModel>> getBudgetsByUser(String userId) async {
    final all = await getAllBudgets();
    return all.where((b) => b.userId == userId).toList();
  }

  static Future<void> deleteBudget(String id) async {
    await _budgetBoxInstance.delete(id);
  }

  static Future<void> clearBudgets() async {
    await _budgetBoxInstance.clear();
  }

  // ============================================================
  // GOALS
  // ============================================================

  static Future<void> saveGoal(GoalModel goal) async {
    await _goalBoxInstance.put(goal.id, jsonEncode(goal.toJson()));
  }

  static Future<GoalModel?> getGoal(String id) async {
    final data = _goalBoxInstance.get(id);
    if (data == null) return null;
    return GoalModel.fromJson(jsonDecode(data));
  }

  static Future<List<GoalModel>> getAllGoals() async {
    final goals = <GoalModel>[];
    for (var key in _goalBoxInstance.keys) {
      final data = _goalBoxInstance.get(key);
      if (data != null) {
        goals.add(GoalModel.fromJson(jsonDecode(data)));
      }
    }
    return goals;
  }

  static Future<List<GoalModel>> getGoalsByUser(String userId) async {
    final all = await getAllGoals();
    return all.where((g) => g.userId == userId).toList();
  }

  static Future<void> deleteGoal(String id) async {
    await _goalBoxInstance.delete(id);
  }

  static Future<void> clearGoals() async {
    await _goalBoxInstance.clear();
  }

  // ============================================================
  // CATEGORIES
  // ============================================================

  static Future<void> saveCategory(CategoryModel category) async {
    await _categoryBoxInstance.put(category.id, jsonEncode(category.toJson()));
  }

  static Future<CategoryModel?> getCategory(String id) async {
    final data = _categoryBoxInstance.get(id);
    if (data == null) return null;
    return CategoryModel.fromJson(jsonDecode(data));
  }

  static Future<List<CategoryModel>> getAllCategories() async {
    final categories = <CategoryModel>[];
    for (var key in _categoryBoxInstance.keys) {
      final data = _categoryBoxInstance.get(key);
      if (data != null) {
        categories.add(CategoryModel.fromJson(jsonDecode(data)));
      }
    }
    return categories;
  }

  static Future<List<CategoryModel>> getCategoriesByUser(String userId) async {
    final all = await getAllCategories();
    return all.where((c) => c.userId == userId).toList();
  }

  static Future<void> deleteCategory(String id) async {
    await _categoryBoxInstance.delete(id);
  }

  static Future<void> clearCategories() async {
    await _categoryBoxInstance.clear();
  }

  // ============================================================
  // NOTIFICATIONS
  // ============================================================

  static Future<void> saveNotification(NotificationModel notification) async {
    await _notificationBoxInstance.put(notification.id, jsonEncode(notification.toJson()));
  }

  static Future<NotificationModel?> getNotification(String id) async {
    final data = _notificationBoxInstance.get(id);
    if (data == null) return null;
    return NotificationModel.fromJson(jsonDecode(data));
  }

  static Future<List<NotificationModel>> getAllNotifications() async {
    final notifications = <NotificationModel>[];
    for (var key in _notificationBoxInstance.keys) {
      final data = _notificationBoxInstance.get(key);
      if (data != null) {
        notifications.add(NotificationModel.fromJson(jsonDecode(data)));
      }
    }
    return notifications;
  }

  static Future<List<NotificationModel>> getNotificationsByUser(String userId) async {
    final all = await getAllNotifications();
    return all.where((n) => n.userId == userId).toList();
  }

  static Future<void> deleteNotification(String id) async {
    await _notificationBoxInstance.delete(id);
  }

  static Future<void> clearNotifications() async {
    await _notificationBoxInstance.clear();
  }

  // ============================================================
  // BACKUPS
  // ============================================================

  static Future<void> saveBackup(BackupModel backup) async {
    await _backupBoxInstance.put(backup.id, jsonEncode(backup.toJson()));
  }

  static Future<BackupModel?> getBackup(String id) async {
    final data = _backupBoxInstance.get(id);
    if (data == null) return null;
    return BackupModel.fromJson(jsonDecode(data));
  }

  static Future<List<BackupModel>> getAllBackups() async {
    final backups = <BackupModel>[];
    for (var key in _backupBoxInstance.keys) {
      final data = _backupBoxInstance.get(key);
      if (data != null) {
        backups.add(BackupModel.fromJson(jsonDecode(data)));
      }
    }
    return backups;
  }

  static Future<List<BackupModel>> getBackupsByUser(String userId) async {
    final all = await getAllBackups();
    return all.where((b) => b.userId == userId).toList();
  }

  static Future<void> deleteBackup(String id) async {
    await _backupBoxInstance.delete(id);
  }

  static Future<void> clearBackups() async {
    await _backupBoxInstance.clear();
  }

  // ============================================================
  // TRANSFERS
  // ============================================================

  static Future<void> saveTransfer(TransferModel transfer) async {
    await _transferBoxInstance.put(transfer.id, jsonEncode(transfer.toJson()));
  }

  static Future<TransferModel?> getTransfer(String id) async {
    final data = _transferBoxInstance.get(id);
    if (data == null) return null;
    return TransferModel.fromJson(jsonDecode(data));
  }

  static Future<List<TransferModel>> getAllTransfers() async {
    final transfers = <TransferModel>[];
    for (var key in _transferBoxInstance.keys) {
      final data = _transferBoxInstance.get(key);
      if (data != null) {
        transfers.add(TransferModel.fromJson(jsonDecode(data)));
      }
    }
    return transfers;
  }

  static Future<List<TransferModel>> getTransfersByUser(String userId) async {
    final all = await getAllTransfers();
    return all.where((t) => t.fromUserId == userId || t.toUserId == userId).toList();
  }

  static Future<void> deleteTransfer(String id) async {
    await _transferBoxInstance.delete(id);
  }

  static Future<void> clearTransfers() async {
    await _transferBoxInstance.clear();
  }

  // ============================================================
  // REPORTS
  // ============================================================

  static Future<void> saveReport(ReportModel report) async {
    await _reportBoxInstance.put(report.id, jsonEncode(report.toJson()));
  }

  static Future<ReportModel?> getReport(String id) async {
    final data = _reportBoxInstance.get(id);
    if (data == null) return null;
    return ReportModel.fromJson(jsonDecode(data));
  }

  static Future<List<ReportModel>> getAllReports() async {
    final reports = <ReportModel>[];
    for (var key in _reportBoxInstance.keys) {
      final data = _reportBoxInstance.get(key);
      if (data != null) {
        reports.add(ReportModel.fromJson(jsonDecode(data)));
      }
    }
    return reports;
  }

  static Future<List<ReportModel>> getReportsByUser(String userId) async {
    final all = await getAllReports();
    return all.where((r) => r.userId == userId).toList();
  }

  static Future<void> deleteReport(String id) async {
    await _reportBoxInstance.delete(id);
  }

  static Future<void> clearReports() async {
    await _reportBoxInstance.clear();
  }

  // ============================================================
  // SHARED PREFERENCES
  // ============================================================

  static Future<void> setString(String key, String value) async {
    await _prefs.setString(key, value);
  }

  static String? getString(String key) {
    return _prefs.getString(key);
  }

  static Future<void> setInt(String key, int value) async {
    await _prefs.setInt(key, value);
  }

  static int? getInt(String key) {
    return _prefs.getInt(key);
  }

  static Future<void> setBool(String key, bool value) async {
    await _prefs.setBool(key, value);
  }

  static bool? getBool(String key) {
    return _prefs.getBool(key);
  }

  static Future<void> setDouble(String key, double value) async {
    await _prefs.setDouble(key, value);
  }

  static double? getDouble(String key) {
    return _prefs.getDouble(key);
  }

  static Future<void> setStringList(String key, List<String> value) async {
    await _prefs.setStringList(key, value);
  }

  static List<String>? getStringList(String key) {
    return _prefs.getStringList(key);
  }

  static Future<void> removePref(String key) async {
    await _prefs.remove(key);
  }

  static Future<void> clearPrefs() async {
    await _prefs.clear();
  }

  // ============================================================
  // CLEAR ALL DATA
  // ============================================================

  static Future<void> clearAllData() async {
    await clearUsers();
    await clearTransactions();
    await clearFamilies();
    await clearBudgets();
    await clearGoals();
    await clearCategories();
    await clearNotifications();
    await clearBackups();
    await clearTransfers();
    await clearReports();
    await clearPrefs();
  }

  // ============================================================
  // SIZE INFO
  // ============================================================

  static int getUserCount() => _userBoxInstance.length;
  static int getTransactionCount() => _transactionBoxInstance.length;
  static int getFamilyCount() => _familyBoxInstance.length;
  static int getBudgetCount() => _budgetBoxInstance.length;
  static int getGoalCount() => _goalBoxInstance.length;
  static int getCategoryCount() => _categoryBoxInstance.length;
  static int getNotificationCount() => _notificationBoxInstance.length;
  static int getBackupCount() => _backupBoxInstance.length;
  static int getTransferCount() => _transferBoxInstance.length;
  static int getReportCount() => _reportBoxInstance.length;

  static int getTotalBoxCount() {
    return _userBoxInstance.length +
        _transactionBoxInstance.length +
        _familyBoxInstance.length +
        _budgetBoxInstance.length +
        _goalBoxInstance.length +
        _categoryBoxInstance.length +
        _notificationBoxInstance.length +
        _backupBoxInstance.length +
        _transferBoxInstance.length +
        _reportBoxInstance.length;
  }
}
