import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive/hive.dart';

// ✅ FIXED: Commented out - generated by build_runner
// part 'goal_model.g.dart';

@HiveType(typeId: 8)
class GoalModel extends HiveObject {
  @HiveField(0)
  String? id;

  @HiveField(1)
  String? userId;

  @HiveField(2)
  String? familyId;

  @HiveField(3)
  String? name;

  @HiveField(4)
  String? description;

  @HiveField(5)
  double? targetAmount;

  @HiveField(6)
  double? currentAmount;

  @HiveField(7)
  DateTime? deadline;

  @HiveField(8)
  String? category; // e.g., Savings, Debt, Vacation, Education, Emergency

  @HiveField(9)
  String? icon;

  @HiveField(10)
  String? color;

  @HiveField(11)
  DateTime? createdAt;

  @HiveField(12)
  DateTime? updatedAt;

  @HiveField(13)
  bool? isCompleted;

  @HiveField(14)
  DateTime? completedAt;

  @HiveField(15)
  String? notes;

  @HiveField(16)
  List<GoalContribution>? contributions;

  GoalModel({
    this.id,
    this.userId,
    this.familyId,
    this.name,
    this.description,
    this.targetAmount,
    this.currentAmount = 0.0,
    this.deadline,
    this.category,
    this.icon,
    this.color,
    this.createdAt,
    this.updatedAt,
    this.isCompleted = false,
    this.completedAt,
    this.notes,
    this.contributions,
  });

  // Safe Timestamp parser
  static DateTime _parseTimestamp(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    return DateTime.now();
  }

  // Safe double parser
  static double _parseDouble(dynamic value) {
    if (value == null) return 0.0;
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    if (value is num) return value.toDouble();
    return 0.0;
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'familyId': familyId,
      'name': name,
      'description': description,
      'targetAmount': targetAmount,
      'currentAmount': currentAmount,
      'deadline': deadline != null ? Timestamp.fromDate(deadline!) : null,
      'category': category,
      'icon': icon,
      'color': color,
      'createdAt': createdAt != null ? Timestamp.fromDate(createdAt!) : null,
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
      'isCompleted': isCompleted,
      'completedAt': completedAt != null ? Timestamp.fromDate(completedAt!) : null,
      'notes': notes,
      'contributions': contributions?.map((c) => c.toJson()).toList() ?? [],
    };
  }

  factory GoalModel.fromJson(Map<String, dynamic> json) {
    return GoalModel(
      id: json['id'] ?? '',
      userId: json['userId'] ?? '',
      familyId: json['familyId'],
      name: json['name'] ?? 'Goal',
      description: json['description'],
      targetAmount: _parseDouble(json['targetAmount']),
      currentAmount: _parseDouble(json['currentAmount']),
      deadline: _parseTimestamp(json['deadline']),
      category: json['category'],
      icon: json['icon'],
      color: json['color'],
      createdAt: _parseTimestamp(json['createdAt']),
      updatedAt: _parseTimestamp(json['updatedAt']),
      isCompleted: json['isCompleted'] ?? false,
      completedAt: _parseTimestamp(json['completedAt']),
      notes: json['notes'],
      contributions: json['contributions'] != null
          ? (json['contributions'] as List)
              .map((c) => GoalContribution.fromJson(c))
              .toList()
          : [],
    );
  }

  GoalModel copyWith({
    String? id,
    String? userId,
    String? familyId,
    String? name,
    String? description,
    double? targetAmount,
    double? currentAmount,
    DateTime? deadline,
    String? category,
    String? icon,
    String? color,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isCompleted,
    DateTime? completedAt,
    String? notes,
    List<GoalContribution>? contributions,
  }) {
    return GoalModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      familyId: familyId ?? this.familyId,
      name: name ?? this.name,
      description: description ?? this.description,
      targetAmount: targetAmount ?? this.targetAmount,
      currentAmount: currentAmount ?? this.currentAmount,
      deadline: deadline ?? this.deadline,
      category: category ?? this.category,
      icon: icon ?? this.icon,
      color: color ?? this.color,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isCompleted: isCompleted ?? this.isCompleted,
      completedAt: completedAt ?? this.completedAt,
      notes: notes ?? this.notes,
      contributions: contributions ?? this.contributions,
    );
  }

  // ==================== HELPERS ====================

  String get displayName => name ?? 'Goal';

  double get progress {
    if (targetAmount == null || targetAmount == 0) return 0.0;
    return ((currentAmount ?? 0.0) / targetAmount!).clamp(0.0, 1.0);
  }

  bool get isAchieved => progress >= 1.0;

  String get formattedTarget => '\$${targetAmount?.toStringAsFixed(2) ?? '0.00'}';
  String get formattedCurrent => '\$${currentAmount?.toStringAsFixed(2) ?? '0.00'}';
  String get remainingAmount => '\$${((targetAmount ?? 0.0) - (currentAmount ?? 0.0)).toStringAsFixed(2)}';

  bool get isOverdue {
    if (deadline == null) return false;
    return deadline!.isBefore(DateTime.now()) && !isAchieved;
  }

  bool get isOnTrack {
    if (deadline == null || targetAmount == null || targetAmount == 0) return false;
    final daysLeft = deadline!.difference(DateTime.now()).inDays;
    if (daysLeft <= 0) return false;
    final totalDays = deadline!.difference(createdAt ?? DateTime.now()).inDays;
    if (totalDays <= 0) return false;
    final expectedProgress = 1 - (daysLeft / totalDays);
    return progress >= expectedProgress;
  }

  GoalModel addContribution(double amount, {String? note}) {
    final newContributions = List<GoalContribution>.from(contributions ?? []);
    newContributions.add(GoalContribution(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      amount: amount,
      note: note,
      date: DateTime.now(),
    ));

    return copyWith(
      currentAmount: (currentAmount ?? 0.0) + amount,
      contributions: newContributions,
      updatedAt: DateTime.now(),
      isCompleted: (currentAmount ?? 0.0) + amount >= (targetAmount ?? 0.0),
      completedAt: (currentAmount ?? 0.0) + amount >= (targetAmount ?? 0.0) 
          ? DateTime.now() 
          : null,
    );
  }
}

// ==================== GOAL CONTRIBUTION MODEL ====================

@HiveType(typeId: 9)
class GoalContribution extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final double amount;
  
  @HiveField(2)
  final DateTime date;
  
  @HiveField(3)
  final String? note;
  
  @HiveField(4)
  final String? transactionId;

  GoalContribution({
    required this.id,
    required this.amount,
    required this.date,
    this.note,
    this.transactionId,
  });

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'amount': amount,
      'date': Timestamp.fromDate(date),
      'note': note,
      'transactionId': transactionId,
    };
  }

  factory GoalContribution.fromJson(Map<String, dynamic> json) {
    return GoalContribution(
      id: json['id'] ?? '',
      amount: (json['amount'] as num?)?.toDouble() ?? 0.0,
      date: (json['date'] as Timestamp?)?.toDate() ?? DateTime.now(),
      note: json['note'],
      transactionId: json['transactionId'],
    );
  }

  GoalContribution copyWith({
    String? id,
    double? amount,
    DateTime? date,
    String? note,
    String? transactionId,
  }) {
    return GoalContribution(
      id: id ?? this.id,
      amount: amount ?? this.amount,
      date: date ?? this.date,
      note: note ?? this.note,
      transactionId: transactionId ?? this.transactionId,
    );
  }
}
