// lib/models/report_model.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive/hive.dart';
import 'package:flutter/material.dart';

// ✅ FIXED: Commented out - generated by build_runner
// part 'report_model.g.dart';

// ==================== REPORT TYPE ENUM ====================

@HiveType(typeId: 20)
enum ReportType {
  @HiveField(0)
  spendingBreakdown,
  @HiveField(1)
  incomeVsExpense,
  @HiveField(2)
  monthlyTrends,
  @HiveField(3)
  categoryWise,
  @HiveField(4)
  budgetPerformance,
  @HiveField(5)
  cashFlow,
  @HiveField(6)
  profitLoss,
  @HiveField(7)
  yearOverYear,
}

// ==================== REPORT MODEL ====================

@HiveType(typeId: 21)
class ReportModel extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String userId;

  @HiveField(2)
  final String? familyId;

  @HiveField(3)
  final ReportType type;

  @HiveField(4)
  final String name;

  @HiveField(5)
  final String? description;

  @HiveField(6)
  final DateTime startDate;

  @HiveField(7)
  final DateTime endDate;

  @HiveField(8)
  final Map<String, dynamic> data;

  @HiveField(9)
  final DateTime generatedAt;

  @HiveField(10)
  final String? generatedBy;

  @HiveField(11)
  final bool isFavorite;

  @HiveField(12)
  final String? exportUrl;

  @HiveField(13)
  final String? format; // 'pdf', 'csv'

  ReportModel({
    required this.id,
    required this.userId,
    this.familyId,
    required this.type,
    required this.name,
    this.description,
    required this.startDate,
    required this.endDate,
    required this.data,
    required this.generatedAt,
    this.generatedBy,
    this.isFavorite = false,
    this.exportUrl,
    this.format,
  });

  // Safe Timestamp parser
  static DateTime _parseTimestamp(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    return DateTime.now();
  }

  // Safe double parser
  static double _parseDouble(dynamic value) {
    if (value == null) return 0.0;
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    if (value is num) return value.toDouble();
    return 0.0;
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'familyId': familyId,
      'type': type.name,
      'name': name,
      'description': description,
      'startDate': Timestamp.fromDate(startDate),
      'endDate': Timestamp.fromDate(endDate),
      'data': data,
      'generatedAt': Timestamp.fromDate(generatedAt),
      'generatedBy': generatedBy,
      'isFavorite': isFavorite,
      'exportUrl': exportUrl,
      'format': format,
    };
  }

  factory ReportModel.fromJson(Map<String, dynamic> json) {
    return ReportModel(
      id: json['id'] ?? '',
      userId: json['userId'] ?? '',
      familyId: json['familyId'],
      type: _parseReportType(json['type']),
      name: json['name'] ?? 'Report',
      description: json['description'],
      startDate: _parseTimestamp(json['startDate']),
      endDate: _parseTimestamp(json['endDate']),
      data: json['data'] ?? {},
      generatedAt: _parseTimestamp(json['generatedAt']),
      generatedBy: json['generatedBy'],
      isFavorite: json['isFavorite'] ?? false,
      exportUrl: json['exportUrl'],
      format: json['format'],
    );
  }

  static ReportType _parseReportType(dynamic value) {
    if (value == null) return ReportType.spendingBreakdown;
    if (value is ReportType) return value;
    if (value is String) {
      try {
        return ReportType.values.firstWhere(
          (e) => e.name == value,
          orElse: () => ReportType.spendingBreakdown,
        );
      } catch (_) {
        return ReportType.spendingBreakdown;
      }
    }
    return ReportType.spendingBreakdown;
  }

  ReportModel copyWith({
    String? id,
    String? userId,
    String? familyId,
    ReportType? type,
    String? name,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
    Map<String, dynamic>? data,
    DateTime? generatedAt,
    String? generatedBy,
    bool? isFavorite,
    String? exportUrl,
    String? format,
  }) {
    return ReportModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      familyId: familyId ?? this.familyId,
      type: type ?? this.type,
      name: name ?? this.name,
      description: description ?? this.description,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      data: data ?? this.data,
      generatedAt: generatedAt ?? this.generatedAt,
      generatedBy: generatedBy ?? this.generatedBy,
      isFavorite: isFavorite ?? this.isFavorite,
      exportUrl: exportUrl ?? this.exportUrl,
      format: format ?? this.format,
    );
  }

  // ==================== HELPERS ====================

  String get typeDisplay {
    switch (type) {
      case ReportType.spendingBreakdown:
        return 'Spending Breakdown';
      case ReportType.incomeVsExpense:
        return 'Income vs Expense';
      case ReportType.monthlyTrends:
        return 'Monthly Trends';
      case ReportType.categoryWise:
        return 'Category-wise Spending';
      case ReportType.budgetPerformance:
        return 'Budget Performance';
      case ReportType.cashFlow:
        return 'Cash Flow';
      case ReportType.profitLoss:
        return 'Profit/Loss';
      case ReportType.yearOverYear:
        return 'Year-over-Year';
    }
  }

  IconData get typeIcon {
    switch (type) {
      case ReportType.spendingBreakdown:
        return Icons.pie_chart;
      case ReportType.incomeVsExpense:
        return Icons.show_chart;
      case ReportType.monthlyTrends:
        return Icons.trending_up;
      case ReportType.categoryWise:
        return Icons.category;
      case ReportType.budgetPerformance:
        return Icons.speed;
      case ReportType.cashFlow:
        return Icons.assessment;
      case ReportType.profitLoss:
        return Icons.attach_money;
      case ReportType.yearOverYear:
        return Icons.calendar_today;
    }
  }

  Color get typeColor {
    switch (type) {
      case ReportType.spendingBreakdown:
        return Colors.blue;
      case ReportType.incomeVsExpense:
        return Colors.green;
      case ReportType.monthlyTrends:
        return Colors.orange;
      case ReportType.categoryWise:
        return Colors.purple;
      case ReportType.budgetPerformance:
        return Colors.teal;
      case ReportType.cashFlow:
        return Colors.cyan;
      case ReportType.profitLoss:
        return Colors.red;
      case ReportType.yearOverYear:
        return Colors.indigo;
    }
  }

  String get dateRange => '${_formatDate(startDate)} - ${_formatDate(endDate)}';

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }

  int get durationInDays => endDate.difference(startDate).inDays + 1;

  Map<String, dynamic> get summary {
    final totalIncome = _parseDouble(data['totalIncome']);
    final totalExpense = _parseDouble(data['totalExpense']);
    final netAmount = totalIncome - totalExpense;

    return {
      'totalIncome': totalIncome,
      'totalExpense': totalExpense,
      'netAmount': netAmount,
      'transactionCount': data['transactionCount'] ?? 0,
      'categoryCount': data['categoryCount'] ?? 0,
      'averageDaily': totalExpense / durationInDays,
    };
  }

  bool get hasIncome => _parseDouble(data['totalIncome']) > 0;
  bool get hasExpense => _parseDouble(data['totalExpense']) > 0;
  bool get hasData => data.isNotEmpty;
}

// ==================== REPORT FILTER MODEL ====================

@HiveType(typeId: 22)
class ReportFilterModel extends HiveObject {
  @HiveField(0)
  final DateTime startDate;

  @HiveField(1)
  final DateTime endDate;

  @HiveField(2)
  final String? category;

  @HiveField(3)
  final String? type; // 'income', 'expense', 'all'

  @HiveField(4)
  final String? familyId;

  @HiveField(5)
  final String? memberId;

  @HiveField(6)
  final double? minAmount;

  @HiveField(7)
  final double? maxAmount;

  @HiveField(8)
  final List<String>? tags;

  @HiveField(9)
  final bool includeTransfers;

  ReportFilterModel({
    required this.startDate,
    required this.endDate,
    this.category,
    this.type,
    this.familyId,
    this.memberId,
    this.minAmount,
    this.maxAmount,
    this.tags,
    this.includeTransfers = false,
  });

  Map<String, dynamic> toJson() {
    return {
      'startDate': Timestamp.fromDate(startDate),
      'endDate': Timestamp.fromDate(endDate),
      'category': category,
      'type': type,
      'familyId': familyId,
      'memberId': memberId,
      'minAmount': minAmount,
      'maxAmount': maxAmount,
      'tags': tags,
      'includeTransfers': includeTransfers,
    };
  }

  factory ReportFilterModel.fromJson(Map<String, dynamic> json) {
    return ReportFilterModel(
      startDate: (json['startDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      endDate: (json['endDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      category: json['category'],
      type: json['type'],
      familyId: json['familyId'],
      memberId: json['memberId'],
      minAmount: (json['minAmount'] as num?)?.toDouble(),
      maxAmount: (json['maxAmount'] as num?)?.toDouble(),
      tags: json['tags'] != null ? List<String>.from(json['tags']) : null,
      includeTransfers: json['includeTransfers'] ?? false,
    );
  }

  ReportFilterModel copyWith({
    DateTime? startDate,
    DateTime? endDate,
    String? category,
    String? type,
    String? familyId,
    String? memberId,
    double? minAmount,
    double? maxAmount,
    List<String>? tags,
    bool? includeTransfers,
  }) {
    return ReportFilterModel(
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      category: category ?? this.category,
      type: type ?? this.type,
      familyId: familyId ?? this.familyId,
      memberId: memberId ?? this.memberId,
      minAmount: minAmount ?? this.minAmount,
      maxAmount: maxAmount ?? this.maxAmount,
      tags: tags ?? this.tags,
      includeTransfers: includeTransfers ?? this.includeTransfers,
    );
  }

  bool get isDefault {
    return category == null &&
        type == null &&
        familyId == null &&
        memberId == null &&
        minAmount == null &&
        maxAmount == null &&
        tags == null &&
        includeTransfers == false;
  }
}
