import 'package:flutter/material.dart';
import 'package:hive/hive.dart';

// ✅ FIXED: Commented out - generated by build_runner
// part 'transaction_model.g.dart';

@HiveType(typeId: 1)
class TransactionModel extends HiveObject {
  @HiveField(0)
  String? id;

  @HiveField(1)
  String? userId;

  @HiveField(2)
  double? amount;

  @HiveField(3)
  String? category;

  @HiveField(4)
  String? description;

  @HiveField(5)
  String? type;

  @HiveField(6)
  DateTime? date;

  @HiveField(7)
  String? notes;

  @HiveField(8)
  DateTime? createdAt;

  @HiveField(9)
  String? familyId;

  @HiveField(10)
  String? memberId;

  @HiveField(11)
  String? memberName;

  @HiveField(12)
  bool? isFamilyTransaction;

  @HiveField(13)
  String? sourceMemberId;

  @HiveField(14)
  String? sourceMemberName;

  @HiveField(15)
  String? transferId;

  @HiveField(16)
  String? transferStatus;

  @HiveField(17)
  String? originalCurrency;

  @HiveField(18)
  double? originalAmount;

  @HiveField(19)
  String? baseCurrency;

  @HiveField(20)
  double? amountInBaseCurrency;

  @HiveField(21)
  double? exchangeRateUsed;

  @HiveField(22)
  bool? isRecurring;

  @HiveField(23)
  String? recurringInterval;

  @HiveField(24)
  List<String>? attachments;

  @HiveField(25)
  List<String>? tags;

  @HiveField(26)
  bool? isDeleted;

  @HiveField(27)
  DateTime? deletedAt;

  TransactionModel({
    this.id,
    this.userId,
    this.amount,
    this.category,
    this.description,
    this.type,
    this.date,
    this.notes,
    this.createdAt,
    this.familyId,
    this.memberId,
    this.memberName,
    this.isFamilyTransaction = false,
    this.sourceMemberId,
    this.sourceMemberName,
    this.transferId,
    this.transferStatus,
    this.originalCurrency,
    this.originalAmount,
    this.baseCurrency,
    this.amountInBaseCurrency,
    this.exchangeRateUsed,
    this.isRecurring = false,
    this.recurringInterval,
    this.attachments,
    this.tags,
    this.isDeleted = false,
    this.deletedAt,
  });

  String get formattedAmount {
    if (amount == null) return '\$0.00';
    return '\$${amount!.toStringAsFixed(2)}';
  }

  String get formattedDate {
    if (date == null) return '';
    return '${date!.day}/${date!.month}/${date!.year}';
  }

  String get typeDisplay {
    if (type == 'income') return 'Income';
    if (type == 'transfer') return 'Transfer';
    return 'Expense';
  }

  Color get typeColor {
    if (type == 'income') return Colors.green;
    if (type == 'transfer') return Colors.blue;
    return Colors.red;
  }

  String get categoryDisplay {
    if (category == null) return 'Other';
    return category!.split('_').map((word) =>
      word[0].toUpperCase() + word.substring(1)
    ).join(' ');
  }

  IconData get categoryIcon {
    switch (category) {
      case 'Food': return Icons.restaurant;
      case 'Transport': return Icons.directions_car;
      case 'Shopping': return Icons.shopping_bag;
      case 'Entertainment': return Icons.movie;
      case 'Utilities': return Icons.electric_bolt;
      case 'Rent': return Icons.home;
      case 'Healthcare': return Icons.health_and_safety;
      case 'Education': return Icons.school;
      case 'Salary': return Icons.attach_money;
      case 'Investment': return Icons.trending_up;
      case 'Gift': return Icons.card_giftcard;
      case 'Travel': return Icons.flight;
      case 'Insurance': return Icons.security;
      case 'Pocket Money': return Icons.account_balance_wallet;
      case 'Allowance': return Icons.credit_card;
      default: return Icons.category;
    }
  }

  bool get isTransfer => type == 'transfer';
  bool get isIncome => type == 'income';
  bool get isExpense => type == 'expense';
  bool get isPending => transferStatus == 'pending';
  bool get isApproved => transferStatus == 'approved';
  bool get isRejected => transferStatus == 'rejected';
  bool get isCompleted => transferStatus == 'completed';

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'amount': amount,
      'category': category,
      'description': description,
      'type': type,
      'date': date?.toIso8601String(),
      'notes': notes,
      'createdAt': createdAt?.toIso8601String(),
      'familyId': familyId,
      'memberId': memberId,
      'memberName': memberName,
      'isFamilyTransaction': isFamilyTransaction,
      'sourceMemberId': sourceMemberId,
      'sourceMemberName': sourceMemberName,
      'transferId': transferId,
      'transferStatus': transferStatus,
      'originalCurrency': originalCurrency,
      'originalAmount': originalAmount,
      'baseCurrency': baseCurrency,
      'amountInBaseCurrency': amountInBaseCurrency,
      'exchangeRateUsed': exchangeRateUsed,
      'isRecurring': isRecurring,
      'recurringInterval': recurringInterval,
      'attachments': attachments,
      'tags': tags,
      'isDeleted': isDeleted,
      'deletedAt': deletedAt?.toIso8601String(),
    };
  }

  factory TransactionModel.fromJson(Map<String, dynamic> json) {
    return TransactionModel(
      id: json['id'],
      userId: json['userId'],
      amount: json['amount']?.toDouble(),
      category: json['category'],
      description: json['description'],
      type: json['type'],
      date: json['date'] != null ? DateTime.parse(json['date']) : null,
      notes: json['notes'],
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : null,
      familyId: json['familyId'],
      memberId: json['memberId'],
      memberName: json['memberName'],
      isFamilyTransaction: json['isFamilyTransaction'] ?? false,
      sourceMemberId: json['sourceMemberId'],
      sourceMemberName: json['sourceMemberName'],
      transferId: json['transferId'],
      transferStatus: json['transferStatus'],
      originalCurrency: json['originalCurrency'],
      originalAmount: json['originalAmount']?.toDouble(),
      baseCurrency: json['baseCurrency'],
      amountInBaseCurrency: json['amountInBaseCurrency']?.toDouble(),
      exchangeRateUsed: json['exchangeRateUsed']?.toDouble(),
      isRecurring: json['isRecurring'] ?? false,
      recurringInterval: json['recurringInterval'],
      attachments: json['attachments'] != null 
          ? List<String>.from(json['attachments']) 
          : null,
      tags: json['tags'] != null 
          ? List<String>.from(json['tags']) 
          : null,
      isDeleted: json['isDeleted'] ?? false,
      deletedAt: json['deletedAt'] != null ? DateTime.parse(json['deletedAt']) : null,
    );
  }

  TransactionModel copyWith({
    String? id,
    String? userId,
    double? amount,
    String? category,
    String? description,
    String? type,
    DateTime? date,
    String? notes,
    DateTime? createdAt,
    String? familyId,
    String? memberId,
    String? memberName,
    bool? isFamilyTransaction,
    String? sourceMemberId,
    String? sourceMemberName,
    String? transferId,
    String? transferStatus,
    String? originalCurrency,
    double? originalAmount,
    String? baseCurrency,
    double? amountInBaseCurrency,
    double? exchangeRateUsed,
    bool? isRecurring,
    String? recurringInterval,
    List<String>? attachments,
    List<String>? tags,
    bool? isDeleted,
    DateTime? deletedAt,
  }) {
    return TransactionModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      amount: amount ?? this.amount,
      category: category ?? this.category,
      description: description ?? this.description,
      type: type ?? this.type,
      date: date ?? this.date,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      familyId: familyId ?? this.familyId,
      memberId: memberId ?? this.memberId,
      memberName: memberName ?? this.memberName,
      isFamilyTransaction: isFamilyTransaction ?? this.isFamilyTransaction,
      sourceMemberId: sourceMemberId ?? this.sourceMemberId,
      sourceMemberName: sourceMemberName ?? this.sourceMemberName,
      transferId: transferId ?? this.transferId,
      transferStatus: transferStatus ?? this.transferStatus,
      originalCurrency: originalCurrency ?? this.originalCurrency,
      originalAmount: originalAmount ?? this.originalAmount,
      baseCurrency: baseCurrency ?? this.baseCurrency,
      amountInBaseCurrency: amountInBaseCurrency ?? this.amountInBaseCurrency,
      exchangeRateUsed: exchangeRateUsed ?? this.exchangeRateUsed,
      isRecurring: isRecurring ?? this.isRecurring,
      recurringInterval: recurringInterval ?? this.recurringInterval,
      attachments: attachments ?? this.attachments,
      tags: tags ?? this.tags,
      isDeleted: isDeleted ?? this.isDeleted,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }
}
